[tool.poetry]
name = "twilio_sms_py"
version = "1.0.3"
description = "send text messages from Twilio API"
authors = ["Emile Averill <cloud.dev.apps@averille.com>"]

[tool.poetry.dependencies]
python=">=3.9,<4.0"
twilio="*"
requests="*"
toml="*"

[tool.poetry.dev-dependencies]
black = "*"
coverage = "*"
flake8 = "*"
pre-commit = "*"
pylint = "*"
pytest = "*"
yapf = "*"

[tool.black]
line-length = 80
target-version = ["py39"]

[tool.yapf]
based_on_style = "pep8"
spaces_before_comment = 2

[tool.yapfignore]
ignore_patterns = [
  "temp/**/*.py"
]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
